name: triage
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - duckdb
  - pytorch=2.4
  - torchvision
  - pip
  - tensorflow
  - pip:
      - shap
